language: node_js

node_js:
  - '10'

notifications:
  email: false

services:
  - postgresql

before_script:
  - npm install
  - psql -c 'create database fintech28;' -U postgres

script:
  - npm run test